services:
  myticket.webmvc:
    container_name: myticket-ui
    image: myticket.ui
    build:
      context: .
      dockerfile: MyTicket.UI/Dockerfile
    ports:
      - "80:8080"
  bms.database:
    container_name: myticket-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password1*
    ports:
      - "1433:1433"